import asyncio
import sys
import os
from dotenv import load_dotenv

load_dotenv()

# Ensure backend modules can be imported
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.events.bus import event_bus
from backend.world_model.graph import world_model
from backend.agents.sensor_fusion import SensorFusionAgent
from backend.agents.mission_planner import MissionPlannerAgent
from backend.agents.incident_commander import IncidentCommanderAgent
from backend.events.domain import HumanApproved

async def run_tests():
    print("=== SentinelOS Complete Architecture Test ===\n")

    print("[1] Initializing Agents...")
    sensor_fusion = SensorFusionAgent()
    mission_planner = MissionPlannerAgent()
    incident_commander = IncidentCommanderAgent()
    print("Agents initialized and subscribed to Event Bus.\n")

    print("[2] Simulating Passive Sensor Network (Incident Detection)")
    # Simulate a flood crisis with high confidence
    await sensor_fusion.ingest_signals(
        latitude=10.0559, 
        longitude=76.6497, 
        signals=["High water levels at Periyar gauge", "Voice distress: 'Vellam', 'Help'"], 
        context={"flood_risk": 0.8}
    )

    # Let the async event loop process the events
    await asyncio.sleep(1)

    print("\n[3] Simulating Human Break-Glass Approval")
    # Simulate human approval for the generated mission
    # Get the generated mission ID from world model
    missions = world_model.get_nodes_by_label("Mission")
    if missions:
        mission = missions[0]
        approval_event = HumanApproved(
            event_id="test-approval-1",
            source="Human",
            action_id=mission.node_id,
            approver_id="Admin-01",
            reasoning="Emergency requires immediate deployment. Privacy restrictions lifted for routing."
        )
        await event_bus.publish(approval_event)
        await asyncio.sleep(1)
    else:
        print("Error: No mission was generated by the Mission Planner.")

    print("\n[4] Verifying World Model State")
    incidents = world_model.get_nodes_by_label("Incident")
    missions = world_model.get_nodes_by_label("Mission")
    print(f"Total Incidents tracked: {len(incidents)}")
    for i in incidents:
        print(f"  - Incident ID: {i.node_id}, Type: {i.properties.get('type')}, Severity: {i.properties.get('severity')}")
    
    print(f"Total Missions generated: {len(missions)}")
    for m in missions:
        print(f"  - Mission ID: {m.node_id}, Required Skills: {m.properties.get('skills')}, Status: {m.properties.get('status')}")
        
        # Check edges
        adjacent = world_model.get_adjacent_nodes(m.node_id, relation="ADDRESSES")
        for adj in adjacent:
            print(f"    -> Addresses Incident: {adj.node_id}")

    print("\n[5] Auditing Immutable Event Bus Logs")
    history = event_bus.get_history()
    print(f"Total Events Logged: {len(history)}")
    for e in history:
        print(f"  [{e.timestamp}] {e.__class__.__name__} from {e.source}")

    print("\n=== Test Completed Successfully ===")

if __name__ == "__main__":
    asyncio.run(run_tests())
