export const MOCK_VOLUNTEERS = [
  {
    id: 'v001',
    name: 'Rajan Mathew',
    phone: '+919847123456',
    skills: ['Doctor', 'First Aid'],
    assets: ['First Aid Kit'],
    languages: ['Malayalam', 'English'],
    lat: 10.0612,
    lng: 76.6523,
    breakGlassLocked: true,
    registeredAt: '2024-01-15',
    available: true,
  },
  {
    id: 'v002',
    name: 'Ancy Joseph',
    phone: '+919746512301',
    skills: ['Nurse', 'First Aid'],
    assets: ['First Aid Kit'],
    languages: ['Malayalam', 'English', 'Hindi'],
    lat: 10.0584,
    lng: 76.6462,
    breakGlassLocked: true,
    registeredAt: '2024-01-17',
    available: true,
  },
  {
    id: 'v003',
    name: 'Dr. Nidhin Varghese',
    phone: '+919495601122',
    skills: ['Doctor', 'Translator'],
    assets: ['First Aid Kit'],
    languages: ['Malayalam', 'English', 'Tamil'],
    lat: 10.0669,
    lng: 76.6416,
    breakGlassLocked: true,
    registeredAt: '2024-01-20',
    available: true,
  },
  {
    id: 'v004',
    name: 'Sheeba Thomas',
    phone: '+919847650998',
    skills: ['Nurse', 'Driver'],
    assets: ['4x4 Vehicle', 'First Aid Kit'],
    languages: ['Malayalam', 'English'],
    lat: 10.0526,
    lng: 76.6578,
    breakGlassLocked: true,
    registeredAt: '2024-01-22',
    available: true,
  },
  {
    id: 'v005',
    name: 'Biju Paul',
    phone: '+919446782345',
    skills: ['Swimmer', 'Boat owner'],
    assets: ['Boat', 'Rope & Rescue Gear'],
    languages: ['Malayalam'],
    lat: 10.0641,
    lng: 76.6538,
    breakGlassLocked: true,
    registeredAt: '2024-02-01',
    available: true,
  },
  {
    id: 'v006',
    name: 'Jomon Xavier',
    phone: '+919497110245',
    skills: ['Swimmer', 'First Aid'],
    assets: ['Rope & Rescue Gear'],
    languages: ['Malayalam', 'English'],
    lat: 10.0498,
    lng: 76.6499,
    breakGlassLocked: true,
    registeredAt: '2024-02-02',
    available: true,
  },
  {
    id: 'v007',
    name: 'Saji Varghese',
    phone: '+919645330198',
    skills: ['Boat owner', 'Driver'],
    assets: ['Boat', '4x4 Vehicle'],
    languages: ['Malayalam', 'Hindi'],
    lat: 10.0704,
    lng: 76.6465,
    breakGlassLocked: true,
    registeredAt: '2024-02-04',
    available: true,
  },
  {
    id: 'v008',
    name: 'Midhun George',
    phone: '+919947530441',
    skills: ['Swimmer', 'Construction'],
    assets: ['Rope & Rescue Gear', 'Chainsaw'],
    languages: ['Malayalam', 'English'],
    lat: 10.0551,
    lng: 76.6428,
    breakGlassLocked: true,
    registeredAt: '2024-02-05',
    available: true,
  },
  {
    id: 'v009',
    name: 'Anoop Kuriakose',
    phone: '+919048762210',
    skills: ['Electrician', 'Generator'],
    assets: ['Generator'],
    languages: ['Malayalam'],
    lat: 10.0637,
    lng: 76.6602,
    breakGlassLocked: true,
    registeredAt: '2024-02-08',
    available: true,
  },
  {
    id: 'v010',
    name: 'Fathima Basheer',
    phone: '+919895442771',
    skills: ['Electrician', 'Translator'],
    assets: ['Generator'],
    languages: ['Malayalam', 'Tamil', 'English'],
    lat: 10.0607,
    lng: 76.6397,
    breakGlassLocked: true,
    registeredAt: '2024-02-10',
    available: true,
  },
  {
    id: 'v011',
    name: 'Rakesh Menon',
    phone: '+919495882365',
    skills: ['Generator', 'Driver'],
    assets: ['Generator', '4x4 Vehicle'],
    languages: ['Malayalam', 'English', 'Hindi'],
    lat: 10.0517,
    lng: 76.6454,
    breakGlassLocked: true,
    registeredAt: '2024-02-11',
    available: true,
  },
  {
    id: 'v012',
    name: 'Jincy Kurian',
    phone: '+919400110972',
    skills: ['Electrician', 'First Aid'],
    assets: ['Generator', 'First Aid Kit'],
    languages: ['Malayalam', 'English'],
    lat: 10.0579,
    lng: 76.6552,
    breakGlassLocked: true,
    registeredAt: '2024-02-15',
    available: true,
  },
  {
    id: 'v013',
    name: 'Suresh Kumar',
    phone: '+919847910234',
    skills: ['Driver', 'Translator'],
    assets: ['4x4 Vehicle'],
    languages: ['Malayalam', 'Tamil', 'Hindi'],
    lat: 10.0688,
    lng: 76.6504,
    breakGlassLocked: true,
    registeredAt: '2024-02-16',
    available: true,
  },
  {
    id: 'v014',
    name: 'Akhil Devassy',
    phone: '+919567440812',
    skills: ['Driver', 'Construction'],
    assets: ['4x4 Vehicle', 'Chainsaw'],
    languages: ['Malayalam', 'English'],
    lat: 10.0543,
    lng: 76.6614,
    breakGlassLocked: true,
    registeredAt: '2024-02-20',
    available: true,
  },
  {
    id: 'v015',
    name: 'Latha Mohan',
    phone: '+919446001553',
    skills: ['Driver', 'First Aid'],
    assets: ['4x4 Vehicle', 'First Aid Kit'],
    languages: ['Malayalam', 'English'],
    lat: 10.0489,
    lng: 76.6517,
    breakGlassLocked: true,
    registeredAt: '2024-02-21',
    available: true,
  },
  {
    id: 'v016',
    name: 'Niyas Rahman',
    phone: '+919847336214',
    skills: ['Driver', 'Boat owner'],
    assets: ['Boat', '4x4 Vehicle'],
    languages: ['Malayalam', 'Kannada', 'English'],
    lat: 10.0596,
    lng: 76.6435,
    breakGlassLocked: true,
    registeredAt: '2024-02-25',
    available: true,
  },
  {
    id: 'v017',
    name: 'Meera Nair',
    phone: '+919495771904',
    skills: ['Translator', 'First Aid'],
    assets: ['First Aid Kit'],
    languages: ['Malayalam', 'English', 'Hindi', 'Tamil'],
    lat: 10.0659,
    lng: 76.6486,
    breakGlassLocked: true,
    registeredAt: '2024-03-01',
    available: true,
  },
  {
    id: 'v018',
    name: 'Arjun Haridas',
    phone: '+919207115830',
    skills: ['Translator', 'Construction'],
    assets: ['Rope & Rescue Gear'],
    languages: ['Malayalam', 'Hindi', 'Kannada'],
    lat: 10.0532,
    lng: 76.6471,
    breakGlassLocked: true,
    registeredAt: '2024-03-04',
    available: true,
  },
  {
    id: 'v019',
    name: 'Roshan Elias',
    phone: '+919605219874',
    skills: ['Doctor', 'Swimmer'],
    assets: ['First Aid Kit', 'Rope & Rescue Gear'],
    languages: ['Malayalam', 'English'],
    lat: 10.0621,
    lng: 76.6447,
    breakGlassLocked: true,
    registeredAt: '2024-03-06',
    available: true,
  },
  {
    id: 'v020',
    name: 'Priya Soman',
    phone: '+919747903216',
    skills: ['Nurse', 'Translator'],
    assets: ['First Aid Kit'],
    languages: ['Malayalam', 'English', 'Tamil', 'Hindi'],
    lat: 10.0566,
    lng: 76.6508,
    breakGlassLocked: true,
    registeredAt: '2024-03-08',
    available: true,
  },
];

export const MOCK_CRISIS_EVENTS = [
  {
    id: 'c001',
    type: 'Flash Flood',
    location: 'Ward 7, Kothamangalam',
    lat: 10.0634,
    lng: 76.6478,
    severity: 'critical',
    confidence: 94,
    reportedAt: new Date(Date.now() - 8 * 60000).toISOString(),
    signals: [
      '14 users in 0.3km radius opened app simultaneously',
      'Google Flood Forecasting API: High alert for Periyar River basin',
      'Traffic standstill detected on Kothamangalam-Munnar Road',
      'Voice keyword spike: "vellam" (flood) detected in area',
      'Weather API: 180mm rainfall in last 6 hours',
      'River gauge: Periyar at 95% capacity',
    ],
    affectedEstimate: '~340 residents',
    status: 'active',
  },
  {
    id: 'c002',
    type: 'Structure Fire',
    location: 'Near KSRTC Bus Stand, Kothamangalam',
    lat: 10.0598,
    lng: 76.6512,
    severity: 'high',
    confidence: 87,
    reportedAt: new Date(Date.now() - 23 * 60000).toISOString(),
    signals: [
      '6 SOS activations in 0.2km radius',
      'Thermal anomaly detected via satellite feed',
      'Multiple reports on Google Maps Live',
    ],
    affectedEstimate: '~80 residents',
    status: 'active',
  },
  {
    id: 'c003',
    type: 'Medical Emergency',
    location: 'Kolenchery Road, Kothamangalam',
    lat: 10.0545,
    lng: 76.6534,
    severity: 'medium',
    confidence: 76,
    reportedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    signals: ['ASHA worker SOS triggered', 'Hospital unavailable — roads blocked'],
    affectedEstimate: '1 critical patient',
    status: 'monitoring',
  },
];

export const MISSION_STATUSES = ['Notified', 'En Route', 'On Site', 'Complete'];
