from typing import Any, Dict
from backend.agents.base import BaseAgent
from backend.events.domain import MissionGenerated, HumanApproved

class IncidentCommanderAgent(BaseAgent):
    """
    The orchestrator agent. Oversees the mission generation and resolves agent debates.
    In the EOC Dashboard, this agent provides the explainable AI interface.
    """
    def __init__(self):
        super().__init__(name="IncidentCommanderAgent")

    def _setup_subscriptions(self):
        self.subscribe(MissionGenerated, self.review_mission)
        self.subscribe(HumanApproved, self.execute_human_override)

    async def review_mission(self, event: MissionGenerated):
        """Reviews missions generated by the Mission Planner."""
        print(f"[{self.name}] Reviewing Mission {event.mission_id} for Incident {event.incident_id}.")
        # Here it might debate with the Privacy Guardian agent about data exposure.
        # For prototype purposes, it simply logs the review.
        print(f"[{self.name}] Mission {event.mission_id} approved for dispatch. Required: {event.required_skills}")

    async def execute_human_override(self, event: HumanApproved):
        """Executes actions approved by the human-in-the-loop (e.g., Break-Glass)."""
        print(f"[{self.name}] Executing Break-Glass protocol. Approver: {event.approver_id}. Reasoning: {event.reasoning}")
        # Proceed with sensitive operations
